### PR TITLE
Updated tools/environment to build on macOS Mojave

### PR DESCRIPTION
**Pull request by Kazzz-S**
@klayoutmatthias 

Attempted to build KLayout on macOS 10.14 Mojave. It was bit painful.
For the time being, it would be better not to build on Mojave since "ruby.h" is not included in the OS.
Please refer to https://github.com/Kazzz-S/klayout/issues/29

Fortunately, binary package built on HighSierra works on Mojave, too (#160).

Regards,
Kazzz

### CODE REVIEW

**Comment by thomaslima** [comment]
Hello @Kazzz-S . I am confused, does the build work in Mojave or not?

I have found a typo in the image you compiled: it says "Ysemite" instead of "Yosemite".

Another question I have is what is the purpose of the scripts KlayoutEditor.sh and KlayoutViewer.sh? People I know have been confused by it and preferred to use the normal Klayout.app bundle, then set it to editor or viewer mode. Besides, I have changed the bundle so that "open with" works with the bundle klayout.app, and set the extension .gds, .gds2 and .oas to Klayout (see Info.plist), which wouldn't if the default app was one of the scripts.

**Comment by Kazzz-S** [comment]
Hello @thomaslima,

Thank you for pointing out the typo. I'll fix it soon.

----

>  I am confused, does the build work in Mojave or not?

I've found "ruby.h" is not included in the current 10.14 macOS.
Therefore build "using OS bundled Ruby as is" fails.
With some workaround (https://github.com/Kazzz-S/klayout/issues/29), I could build in Mojave, too.
So far, the major build problem in Mojave is "missing ruby.h".  I hope the next OS release will fix this.
I have not tried other choices (e.g. Ruby from Homebrew).

----

> Another question I have is what is the purpose of the scripts KlayoutEditor.sh and KlayoutViewer.sh? 

There is a little historical reason.
Earlier (even now?), Windows binary package provided two types of launching icons; one for Editor and another for Viewer. I liked this idea. 
In my main work environment (Linux), I've prepared two icons each of which is passed different "-style" option to Qt. More precisely, with Qt4,  I'm using "plastique" for Editor; "motif" for Viewer.

I wanted to mimic this in Mac, too, several years ago. No change, since then.
If Mac users do not need this (even optionally), we can drop this in future.

Regards,
Kazzz

**Comment by thomaslima** [comment]
Thanks for the explanation!

Best,
Thomas

**Comment by lukasc-ubc** [comment]
I agree. I don’t think the extra Editor/Viewer scripts are necessary. Just the App suffices.

**Comment by thomaslima** [comment]
That looks great to me. Thanks!

On 8 Oct 2018, at 07:25, Kazunari Sekigawa <notifications@github.com<mailto:notifications@github.com>> wrote:


[2018-10-08 19 58 11]<https://user-images.githubusercontent.com/16847255/46606173-dc548800-cb36-11e8-98f8-6da89bcd87e1.png>

How about this? Sorry for not being a good designer!
Kazzz

**Pull request merged**
