### PR TITLE
brew qt 5.12 not supported in osx 10.11, reverting to qt 5.11.2

### PR DESCRIPTION
**Pull request by thomaslima**
Self-explanatory title. I haven't tried hard to fix the installation of qt 5.12. See fail in: https://travis-ci.org/lightwave-lab/klayout/jobs/470707851 :
```
/private/tmp/qt-20181220-68398-rhabbf/qt-everywhere-src-5.12.0/qtbase/bin/qfloat16-tables global/qfloat16tables.cpp
/private/tmp/qt-20181220-68398-rhabbf/qt-everywhere-src-5.12.0/qtbase/bin/rcc -name mimetypes mimetypes/mimetypes.qrc -o .rcc/qrc_mimetypes.cpp
Sorry, "rcc" can not be run on this version of macOS. Qt requires macOS 10.12.0 or later, you have macOS 10.11.6.
make[3]: *** [.rcc/qrc_mimetypes.cpp] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [sub-corelib-make_first] Error 2
make[1]: *** [sub-src-make_first] Error 2
make: *** [module-qtbase-make_first] Error 2
Do not report this issue to Homebrew/brew or Homebrew/core!
Error: You are using macOS 10.11.
We (and Apple) do not provide support for this old version.
You will encounter build failures and other breakages.
Please create pull requests instead of asking for help on Homebrew's
GitHub, Discourse, Twitter or IRC. As you are running this old version,
you are responsible for resolving any issues you experience.
These open issues may also help:
ttfautohint: restore --with-qt option and fix building ttfautohintGUI https://github.com/Homebrew/homebrew-core/pull/35292
```

PS: Soon Travis will include Mojave in their suite of VMs, but El Capitan is losing more and more support.

### CODE REVIEW

**Comment by klayoutmatthias** [comment]
Hi Thomas,

I had conflicts with master (#214 and #213). I tried to fix them - maybe you could review by changes in travis-ci/fix/el-capitan. I kept the MATRIX_EVAL statements but dropped the qt packages for MacOS 10.11. 

Thanks,

Matthias

**Comment by thomaslima** [comment]
It looks alright. Your push triggered this travis-build: https://travis-ci.org/lightwave-lab/klayout/builds/473683817

Once it completes, maybe we can merge with certainty. :)

Happy holidays!

**Comment by thomaslima** [comment]
@klayoutmatthias Travis built the app successfully on El Capitan. I haven't tested it though.

**Comment by thomaslima** [comment]
Hope you don't mind, but since the build passed, I'm going to accept this PR.

**Pull request merged**
